# Generated by Django 5.1.5 on 2025-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difficult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='page_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
